### PR TITLE
v1.0 👁🚀

### PR DESCRIPTION
**Pull request by itsojon**

### CODE REVIEW

**Review by sumeetjain — APPROVED** [review]

**Review by alexk307 — APPROVED** [review]
LFG 🚢

**Review by hugh-sublime — APPROVED** [review]

**Review by bfilar — APPROVED** [review]

**Comment by benjamminj** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Review by ianthiel — APPROVED** [review]
lgtm if it works 👍

**Review by madirey — APPROVED** [review]
Subl-eye-me 👁️

**Review by benjamminj — APPROVED** [review]

**Review by cameron-dunn-sublime — APPROVED** [review]

**Review by jonathanbunce — APPROVED** [review]
🤙

**Review by rw-access — APPROVED** [review]
it's okay

**Review by yungbeaniebaby — APPROVED** [review]
🐸

**Comment by omar-jalalzada** [comment]
please add a 🍋 but otherwise LGTM

**Comment by jkamdjou** [comment]
has this been tested?

**Review by morriscode — APPROVED** [review]
🔥

**Review by omar-jalalzada — APPROVED** [review]
🍋

**Comment by itsojon** [comment]
> has this been tested?

@jkamdjou more than you know.

**Comment by itsojon** [comment]
> has this been tested?

@jkamdjou you know it; how do you think i got these sqars?

**Review by jkamdjou — APPROVED** [review]

**Pull request merged**
